version: "3"
services:
  
  #influxdb:
  #  image: influxdb
  #  restart: always
  #  ports:
  #    - "8087:8086"
  #  expose:
  #    - "8086"
  #  environment:
  #    - DOCKER_INFLUXDB_INIT_MODE=setup
  #    - DOCKER_INFLUXDB_INIT_USERNAME=dbuser
  #    - DOCKER_INFLUXDB_INIT_PASSWORD=password
  #    - DOCKER_INFLUXDB_INIT_ORG=cms-tedd
  #    - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket  
  #  volumes:
  #    - influxdb2:/var/lib/influxdb2
  #    - ./influxdb/config:/etc/influxdb2
  
  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - .output:/output #if no influxdb then write the output file to .txt
    depends_on: 
      - mosquitto
    #  - influxdb
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always
    ports:
      - "1883:1883"
    expose:
      - "1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config

  caen_hvps:
    image: centos:caen_hvps_mqtt_v0.1
    platform: linux/amd64
    build: ../..
    restart: always
    stdin_open: true #docker run -i
    tty: true #docker run -t
    #ports:
    #  - "4000:4000"
    #expose:
    #  - "4000"
    volumes:
      - caen_hvps:/usr/app/caen_hvps
    #depends_on:
    #  - mosquitto    
volumes:
  telegraf.conf:
  #influxdb2:
  mosquitto_data:
  mosquitto_log:
  caen_hvps:


